export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const SET_MESSAGES = 'SET_MESSAGES';
export const INIT_MESSAGES = 'INIT_MESSAGES';
export const FETCH_MESSAGES_FAILED = 'FETCH_MESSAGES_FAILED';
